### ISSUE TITLE
Consider using Gitter for chat

### ISSUE THREAD

**Issue by ihabunek** [robertbasic/pugdebug#106]
I haven't used it much, but seems nice: https://gitter.im/

I often want to discuss stuff with you and have to look around for you on IRC. This is a persistent chat.

**Comment by robertbasic** [comment]
I like how clicking on the "Pricing" link does absolutely nothing. :D

**Comment by robertbasic** [comment]
This is yet another app I have to load. You'll sooner find me on IRC then me remembering to load it up.

**Comment by robertbasic** [comment]
I created a slack team, will that work? https://github.com/robertbasic/pugdebug#slack

**Comment by robertbasic** [comment]
Using slack.
