### ISSUE TITLE
Building on ubuntu

### ISSUE THREAD

**Issue by doublex** [robertbasic/pugdebug#135]
Great work! Definitely the missing tool for PHP development.
Could you explain how to build on Ubuntu?

**Comment by robertbasic** [comment]
Thanks!

Have you tried compiling all the dependencies following my [blog post](http://robertbasic.com/blog/install-pyqt5-in-python-3-virtual-environment)?

**Comment by robertbasic** [comment]
Hey @doublex!

I did my best to document a short and to the point process of setting up everything to run the development version of pugdebug on Ubuntu.

You can read it on the wiki here: https://github.com/robertbasic/pugdebug/wiki/Install-pugdebug#installing-development-version-on-ubuntu

**Comment by doublex** [comment]
Excellent!!
Thanks a lot!
This is most easy.
