### ISSUE TITLE
Mac OS X Mavericks installation

### ISSUE THREAD

**Issue by michaloo** [robertbasic/pugdebug#158]
Hey,

I've just successfully installed `pugdebug` on Mac OS X Mavericks with homebrew.
It was slightly different that FAQ solution, so I wanted to share it:

```
brew install python3
brew install qt5 pyqt5 sip --with-python3
PYTHONPATH=/usr/local/lib/python3.4/site-packages/
pip3 install Pygments
python3 app.py
```

thanks for the project!

**Comment by rdebeasi** [comment]
Works for me as well. Thanks so much!

**Comment by rdebeasi** [comment]
To get this working for me, I also needed to clear out the "host" field in preferences and change the IDE key to "netbeans-xdebug", which is the key provided by The Easiest Xdebug browser plugin. (I could've changed that key in the browser plugin.)

Neither of these are Mac-specific tweaks, but it might be helpful to flesh out the documentation with such tips.

**Comment by robertbasic** [comment]
Thanks, updated the wiki!
