### ISSUE TITLE
Handle trailing slashes in path mappings

### ISSUE THREAD

**Issue by rdebeasi** [robertbasic/pugdebug#159]
When I include trailing slashes in my path mappings, I get the following error: "File does not exist after mapping. Is the path map correct?"

It might be good to either allow for trailing slashes or document the need to leave trailing slashes out. I'm experiencing this behavior with pugdebug 1.0 on Mac OS X.

By the way, pugdebug rocks. Thanks! :)

**Comment by robertbasic** [comment]
Thanks for the report and sorry for the late reply! I'll look into it!

**Comment by rdebeasi** [comment]
Thank you so much! :)

**Comment by robertbasic** [comment]
Thank you for the report! :)
