### ISSUE TITLE
Reload source

### ISSUE THREAD

**Issue by glenreesor** [robertbasic/pugdebug#169]
It would be convenient if there was a reload source button, so you don't have to close and reopen source tabs when you've changed the code. The button would either reload the current source file, or all source files.

**Comment by rdebeasi** [comment]
Alternately, pugdebug could watch files and reload as needed. Many text editors (Sublime, Atom, etc.) do this sort of thing.

Pugdebug rocks, by the way - thanks for building it! :)

**Comment by robertbasic** [comment]
On what OS are you using pugdebug? 

File watching is in there from the start and it's working for me.

https://www.youtube.com/watch?v=EHQa2mKzuKw

**Comment by robertbasic** [comment]
Confirmed bug on Windows, working on a fix now.

Thanks for the report!
