### ISSUE TITLE
Make tab width configurable when viewing source

### ISSUE THREAD

**Issue by glenreesor** [robertbasic/pugdebug#170]
It would be nice if you could change configure the tab width on a pre-project basis.

**Comment by romellem** [comment]
I was looking at this too. 

While it'd be nice if this was configurable somehow, I was able to modify the source code to set the tab width away from its default value.

Open **pugdebug/gui/document.py** and go to PugdebugDocumentContents::\__init\__ (line 161), and add the following line:

```
"""
Change tab width to 20px (default is 80px I think...)
"""
self.setTabStopWidth(20)
```

I placed that after the `self.setPlainText` call, but I'd imagine you could put it anywhere after the `super` call at the top.

**Comment by glenreesor** [comment]
Thanks Robert. Are you still actively developing this? Would you accept pull requests?

- Glen
