### ISSUE TITLE
The requested address is not valid in its context

### ISSUE THREAD

**Issue by MDScranton** [robertbasic/pugdebug#172]
I am connecting to a VirtualBox CentOS system which I am able to use with Sublime Text 3's Xdebug package. I have set up everything the same way in pugdebug and am unable to connect to the remote server. The message returned is verbatim in the subject line.

**Comment by robertbasic** [comment]
Thanks for the report, I'll look into it.

**Comment by robertbasic** [comment]
@MDScranton could you provide your settings? Otherwise I have nothing to go on with.

**Comment by MDScranton** [comment]
Honestly, I don't remember since this was so long ago. I have since changed development environments and the issue no longer affects me.

**Comment by robertbasic** [comment]
Thanks for following up with this, and sorry I didn't get around earlier to
it!

Happy holidays!
