### ISSUE TITLE
Readonly editor cursor

### ISSUE THREAD

**Issue by gerardroche** [robertbasic/pugdebug#179]
The editor is readonly so the cursor should be the same as other non editable windows.

It makes it feel like you can move the highlighted line.

![pugdebug_editor_cursor](https://cloud.githubusercontent.com/assets/44148/17783025/16cf29e4-656e-11e6-9b8f-478118b2da4e.png)

**Comment by robertbasic** [comment]
Implemented with #182, thanks!
