### ISSUE TITLE
Source text of PHP is not displayed

### ISSUE THREAD

**Issue by Sempervivum** [robertbasic/pugdebug#180]
Hallo,
I'm having the problem that pugdebug triggers and says "Debugging in progress ..." at the bottom but doesn't show the source text of the PHP file. The correct filename is displayed in the tab above the window. I can open the file manually by navigating in the file browser at the left and then the source is displayed correctly.
A second project works fine.
There is a blank in the path of the root folder. Might this be the problem? I put the path in quotes but it didn't help.
Any help is appreciated.
Best regards - Ulrich
![pugdebug](https://cloud.githubusercontent.com/assets/6693087/20466858/3f75982c-af7b-11e6-8fd7-08d15388c6df.png)

**Comment by Sempervivum** [comment]
PS: Noticed that this is a duplicate of #157. However the solution described there, using forward slashes for the root path in the settings, did not help. Thus still waiting for a solution.

**Comment by robertbasic** [comment]
Given that the path for Root in the settings window, and the path visible in the stacktraces window are different, I'm guessing there's an incorrect setup of the path mapping, aka the "Maps from" setting should be filled with the mapping.

Please refer to the [pugdebug path settings](https://github.com/robertbasic/pugdebug#pugdebug-path-settings) section
