### ISSUE TITLE
Store the configuration in a file instead of registry ?

### ISSUE THREAD

**Issue by crazy-max** [robertbasic/pugdebug#208]
Hi,

For [Neard project](https://github.com/crazy-max/neard), @N6REJ would like to add pugdebug but the configuration is stored in the registry (crazy-max/neard#265) and it would be nice if you could store it in a file instead ?

**Comment by crazy-max** [comment]
Can you give some news about this feature ?
Thanks!

**Comment by N6REJ** [comment]
Looking @ it carefully I'm thinking it is not really practical.. I dont' see it as being very portable..
https://github.com/robertbasic/pugdebug/wiki/Install-pugdebug#installing-development-version-on-ubuntu
Windows dependencies are even worse.
