### ISSUE TITLE
Strange behaviour of MDI windows

### ISSUE THREAD

**Issue by ihabunek** [robertbasic/pugdebug#57]
To reproduce:
- open pugdebug, 
- click on one of the 4 smaller MDI windows to the right
- resize the main window

Notice that the selected MDI window moved to the left.

**Comment by robertbasic** [comment]
Resize the main window as in maximize/minimize.

Huh, must be some side effect of cascading windows.

**Comment by ihabunek** [comment]
Any resize works. Dragging an edge or corner, as well as maximizing/restoring.

**Comment by robertbasic** [comment]
Well, only max/min for me.

**Comment by robertbasic** [comment]
There appears to be [a few](https://bugreports.qt.io/browse/QTBUG-9598) [bugs](https://bugreports.qt.io/browse/QTBUG-43828) with [tiling](https://bugreports.qt.io/browse/QTBUG-14729) in QT.

**Comment by robertbasic** [comment]
Removed QMdiArea, added QDockWidgets, so this becomes invalid.
