### ISSUE TITLE
Can't assign requested Address

### ISSUE THREAD

**Issue by vranac** [robertbasic/pugdebug#58]
To reproduce on osx:
1. Start pugdebug
2. Change host to another IP
3. Start Debug

Error:
Traceback (most recent call last):
  File "/Users/vranac/dev/pugdebug/pugdebug/server.py", line 194, in __connect_server
    socket_server.bind((host, port_number))
OSError: [Errno 49] Can't assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vranac/dev/pugdebug/pugdebug/server.py", line 66, in run
    response = self.__connect_server()
  File "/Users/vranac/dev/pugdebug/pugdebug/server.py", line 208, in __connect_server
    print(OSError.strerror())
TypeError: 'member_descriptor' object is not callable

**Comment by robertbasic** [comment]
Start pugdebug the application, or start the debugging session?

**Comment by robertbasic** [comment]
Also, what did you enter as the host?

**Comment by vranac** [comment]
Start the application.
Entered 33.33.33.200

**Comment by robertbasic** [comment]
And if you try `33.33.33.1` as the host?

**Comment by vranac** [comment]
Updated the description.
If I enter 33.33.33.1 as the host no error

**Comment by robertbasic** [comment]
Because that's the correct IP to use when debugging inside a vagrant box, as that is the IP PHP "sees" when getting a connection.

`33.33.33.100` is the IP of the vagrant box, whereas `Host` refers to the IP on which pugdebug can be found.

pugdebug should display a nice error message, instead of crapping out with an exception.

**Comment by vranac** [comment]
ooooook, can you please explain how would the host ip be used?

**Comment by robertbasic** [comment]
The host IP is the IP on which xdebug can find pugdebug (or any other remote debugger). http://xdebug.org/docs/remote#communication

**Comment by vranac** [comment]
I do understand the purpose of the host ip, but I am trying to understand the use case when it would need to be configured by hand.

**Comment by vranac** [comment]
After discussing this with @robertbasic I agree about the nice error message.
